app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path("admin/", admin.site.urls),
    path("", include('webapp.urls')),
    path('auth/', include('accounts.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.base import IndexView
from webapp.views.products import ProductDetail, ProductCreateView, ProductUpdateView, ProductDeleteView

urlpatterns =[
    path("", IndexView.as_view(), name='index'),
    path("product/<int:pk>", ProductDetail.as_view(), name='product_detail'),
    path('product/add/', ProductCreateView.as_view(), name='product_add'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/confirm_delete/', ProductDeleteView.as_view(), name='confirm_delete'),
]

webapp/models/products.py
from django.db import models
from django.db.models import TextChoices


class CategoryChoice(TextChoices):
    OTHER = 'other', 'Разное'
    TELEPHONE = 'smartphones', 'Смартфоны'
    LAPTOP = 'laptops', 'Ноутбуки'
    TV = 'TV', 'Телевизоры'


class Product(models.Model):
    name = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name="Наименование товара"
    )
    category = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        choices=CategoryChoice.choices,
        default=CategoryChoice.OTHER,
        verbose_name="Категория товара"
    )
    text = models.TextField(
        max_length=2000,
        null=True,
        blank=True,
        verbose_name="Описание товара"
    )
    photo = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name='Изображение продукта',
        default='blank.jpg'
    )

    average_grade = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name='Средняя Оценка',
        default=0
    )
    average_grade_stars = models.CharField(
        max_length=10,
        null=True,
        blank=True,
        verbose_name='Средняя оценка звездочками',
        default=''
    )

webapp/models/reviews.py
from django.db import models
from django.db.models import TextChoices
from django.contrib.auth.models import User

from webapp.models import Product


class ModerateChoice(TextChoices):
    MODERATE = 'Moderate', 'Модерировано'
    NOMODERATE = 'No_moderate', 'Немодерировано'


class Review(models.Model):
    moderation = models.CharField(
        max_length=50,
        null=False,
        blank=False,
        choices=ModerateChoice.choices,
        default=ModerateChoice.NOMODERATE,
        verbose_name="Модерация"
    )

    author = models.ForeignKey(
        max_length=50,
        null=False,
        blank=False,
        to=User,
        related_name='reviews',
        verbose_name='Автор',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        max_length=50,
        null=False,
        blank=False,
        to=Product,
        related_name='reviews',
        verbose_name='Товары',
        on_delete=models.CASCADE
    )
    text = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name='Текст отзыва'
    )
    grade = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name='Оценка',
        default=0
    )
    grade_stars = models.CharField(
        max_length=10,
        null=True,
        blank=True,
        verbose_name='Оценка звездочками',
        default=''
    )

webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, BaseValidator

from webapp.models import Product


def max_len_validator(string):
    if len(string) > 20:
        raise ValidationError('Заголовок должен быть длиннее 2 символов')
    return string


class CustomLenValidator(BaseValidator):
    def __init__(self, limit_value=20):
        message = 'Максимальная длина заголовка %(limit_value)s. Вы ввели %(show_value)s символов'
        super().__init__(limit_value=limit_value, message=message)

    def compare(self, value, limit_value):
        print(value)
        print(limit_value)
        return value > limit_value

    def clean(self, value):
        return len(value)

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'text', 'photo', 'category']
        labels = {
            'name': 'Наименование',
            'text': 'Описание',
            'photo': 'Изображение',
            'category': 'Категория'
        }

class SearchForm(forms.Form):
    search = forms.CharField(max_length=20, required=False, label='Найти')

webapp/views/base.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import RedirectView, ListView

from webapp.forms import SearchForm
from webapp.models import Product
from webapp.models.products import CategoryChoice


class IndexView(ListView):
    template_name = 'index.html'
    model = Product
    context_object_name = 'products'
    ordering = ('name',)
    paginate_by = 5
    paginate_orphans = 1
    extra_context = {'choices': CategoryChoice.choices}
    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_queryset(self):
        queryset = super().get_queryset().all()     #exclude(is_deleted=True)
        if self.search_value:
            query = Q(name__icontains=self.search_value) | Q(text__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context


class IndexRedirectView(RedirectView):
    pattern_name = 'index'

webapp/views/products.py
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, FormView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy

from webapp.forms import ProductForm
from webapp.models import Product
from webapp.models.products import CategoryChoice


class ProductDetail(DetailView):
    template_name = 'product.html'
    model = Product
    extra_context = {'choices': CategoryChoice.choices}

class GroupPermissionCreateMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name__in=['admin', 'moderator']).exists()

class ProductCreateView(GroupPermissionCreateMixin, SuccessMessageMixin, LoginRequiredMixin, CreateView):
    template_name = 'product_create.html'
    model = Product
    form_class = ProductForm
    success_message = 'Продукт создан'

    def get_success_url(self):
        return reverse('product_detail', kwargs={'pk': self.object.pk})

class GroupPermissionEditMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name__in=['admin', 'moderator']).exists()


class ProductUpdateView(GroupPermissionEditMixin, SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    template_name = 'product_update.html'
    form_class = ProductForm
    model = Product
    success_message = 'Продукт обновлён'

    def get_success_url(self):
        return reverse('product_detail', kwargs={'pk': self.object.pk})

class GroupPermissionDeleteMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name__in=['Admin', 'Manager', 'TeamLead']).exists()

class ProductDeleteView(GroupPermissionDeleteMixin, SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    template_name = 'product_confirm_delete.html'
    model = Product
    success_url = reverse_lazy('index')
    success_message = 'Продукт удалён'

webapp/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Blog{% endblock %}</title>
</head>
<body>
<nav class="navbar">
    <div class="container">
        <ul class="menu">
            <li>
                <a href="{% url 'index' %}" class="btn btn-primary">Home</a>
            </li>
            {% block menu %}{% endblock %}
            {% if user.is_authenticated %}

                <li>
                    <a href="{% url 'profile' user.pk %}" class="btn btn-primary">Profile</a>
                </li>
                <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Выйти">
                    </form>
                </li>
                <li>Привет, {{ user.username }}</li>
            {% else %}
                 <li><a href="{% url 'login' %}" class="btn btn-primary">Войти</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>

webapp/templates/index.html
{% extends 'base.html' %}
{% load l10n %}
{% block title %}Products{% endblock %}
{% block menu %}

{% endblock %}
{% block content %}
{% include 'partial/search.html' %}
<div class="content">
    <div class="product-list">
        {% if products %}
        {% for p in products %}
        <div class="product-item">
            <div class="product-desc">
                <p class="product-title">{{ p.name }}</p>
                {% for choice in choices %}
                    {% if choice.0 == p.category %}
                        <p class="product-category">{{ choice.1 }}</p>
                    {% endif %}
                {% endfor %}
                <p><a href="{% url 'product_detail' p.id %}">see more >>></a></p>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>Products is empty!</p>
        {% endif %}
    </div>
</div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

webapp/templates/product.html
{% extends 'base.html' %}
{% block title %}Product{% endblock %}
{% block menu %}
{% if user.is_authenticated %}
    {% if perms.webapp.change_product %}
    <a href="{% url 'product_update' product.pk%}" class="btn btn-success">Update product</a>
    {% endif %}
    {% if perms.webapp.delete_product %}
    <a href="{% url 'product_delete' product.pk%}" class="btn btn-danger">Delete product</a>
    {% endif %}
    {% if perms.webapp.create_product %}
    <a href="{% url 'product_add' %}" class="btn btn-primary">Product Create</a>
    {% endif %}
{% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Product</h1>
    <p>Title: {{ product.name }}</p>
        {% for choice in choices %}
        {% if choice.0 == product.category %}
        <p class="product-category">Category: {{ choice.1 }}</p>
        {% endif %}
        {% endfor %}
        <p>Text: {{ product.text }}</p>
    <p>Photo: {{ product.photo }}</p>

    {% if product.reviews %}
    {% for  review in product.reviews.all %}
        <p>Пользователь <b>{{ review.user.username }}</b> - Коментарий: {{ review.text }}  - Оценка: {{ review.grade_stars }}</p>
    {% endfor %}
        {% else %}
        <h2>Нет комментариев и оценок!</h2>
        {% endif %}
    </div>
{% endblock %}

webapp/templates/product_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Article confirm delete{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Вы точно хотите удалить статью?</h1>
    <p>Title: {{ product.name }}</p>
    <p>Text: {{ product.text }}</p>
        <form action="{% url 'confirm_delete' product.pk %}" method="post">
            {% csrf_token %}
            <p><input type="submit" value="Удалить"></p>
            <p><a href="{% url 'index' %}">Отмена</a></p>
        </form>
    </div>
{% endblock %}

webapp/templates/product_create.html
{% extends 'base.html' %}
{% block title %}Article Create{% endblock %}
{% block content %}
    <h1>New Article</h1>
<div class="form">
    <form action="{% url 'product_add' %}" method="post">
  {% include 'partial/product_form.html' with button_text='Создать' %}
    </form>
</div>
{% endblock %}

webapp/templates/product_update.html
{% extends 'base.html' %}
{% block title %}Article Create{% endblock %}
{% block content %}
    <h1>New Article</h1>
<div class="form">
    <form action="{% url 'product_update' product.pk %}" method="post">
    {% include 'partial/product_form.html' with button_text='Редактировать' %}
    </form>
</div>
{% endblock %}